### ISSUE TITLE
Экранирование символов 2.

### ISSUE THREAD

**Issue by Mirmik** [pcl-ru/pcl-ru#10]
В догонку к запросу от 22 Oct 2015

chapter-03.tex, строка 283
-  (format t "~{~{~a:~10t~a~%~}~%~}" _db_))
+  (format t "~\{~\{~a:~10t~a~%~\}~%~\}" _db_))

**Comment by catap** [comment]
Привет, а можешь сделать pull request?

**Comment by Mirmik** [comment]
have done
