### ISSUE TITLE
Соберите пожалуйста книгу из исходников

### ISSUE THREAD

**Issue by myCrack** [pcl-ru/pcl-ru#12]
Я сам пытался собирать, но результат получился не очень (просто я никогда раньше не сталкивался с такими файлами, ну те что TEX, почитал про них, но оказалось что там все сложно, и чтобы самому разобраться как нужно делать, уйдет слишком много времени).

Вот здесь http://lisper.ru/pcl/pcl.pdf есть уже собранная книга, но там текст кажется еще со старого перевода, т.е. не обновленный.
И еще, там нету - сносок, некоторых таблиц, картинок, код не выровнен, и врезки показываются как обычный текст.

А в той книжке что у меня получилось собрать -- все ссылки на главы и таблицы выглядят как два вопросительных знака, т.е. вот так `??`, нет оглавления и содержания, также нету отступа между абзацами из-за чего книга очень сложно читается.

Спасибо.

**Comment by alexott** [comment]
https://www.dropbox.com/s/xqx852iwyh7hmrc/pcl-ru.pdf?dl=0 - это копия которая ушла в печать, без последних коммитов
