### ISSUE TITLE
Сделайте релиз в PDF

### ISSUE THREAD

**Issue by egorsmkv** [pcl-ru/pcl-ru#13]
В репозиторий можно загрузить скомпилированный вариант книги.

По данной ссылке не могу скачать книгу:
> lisper.ru/pcl/pcl.pdf

**Comment by alexott** [comment]
Done: https://github.com/pcl-ru/pcl-ru/releases

**Comment by egorsmkv** [comment]
Спасибо!

**Comment by alexott** [comment]
Если найдете ошибки, делайте issue - у меня сейчас больше времени на это :-)

**Comment by egorsmkv** [comment]
Ок.
