### ISSUE TITLE
myverb съела фигурные скобки

### ISSUE THREAD

**Issue by maxnikulin** [pcl-ru/pcl-ru#14]
Страница 101 внизу: в примере с примечанием переводчика (после «Вот несколько примеров цикла DO со скелетом, отмеченным фигурными скобочками вместо обычных*:») потерялись фигурные скобки.

В PDF
``` lisp
do (i 0 (1+ i))
    (>= i 4)
  (print i)
```

chapter-07.tex:454
``` tex
\begin{myverb}
{do {(i 0 (1+ i))}
    {(>= i 4)}
  (print i)}
\end{myverb}
```

**Comment by alexott** [comment]
fixed by #18
