### ISSUE TITLE
Экранирование символов

### ISSUE THREAD

**Issue by sshw** [pcl-ru/pcl-ru#9]
chapter-03.tex

(format t "\~\{\~a:\~10t\~a\~%\~\}\~%" cd)

Надо заменить на

(format t "\~\\{~a:\~10t\~a\~%~\\}\~%" cd)

А то после сборки в pdf (в книге, к стати, то же) получается

(format t "\~\~a:\~10t\~a\~%\~\~%" cd)

**Comment by catap** [comment]
Спасибо, поправил!

**Comment by Mirmik** [comment]
Аналогично нужно изменить и строку 283.
-   (format t "~{~{~a:~10t~a~%~}~%~}" *db*))
+  (format t "~\{~\{~a:~10t~a~%~\}~%~\}" *db*))
